# Generated by Django 5.1.4 on 2025-02-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('expire_date', models.DateField()),
                ('bg_color', models.CharField(max_length=255)),
                ('qrcode_color', models.CharField(max_length=255)),
                ('qrcode_style', models.CharField(max_length=255)),
                ('border_color', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.profile')),
            ],
        ),
    ]
