# Generated by Django 5.1.4 on 2025-02-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCodeApp', '0002_alter_qrcode_bg_color_alter_qrcode_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
