# Generated by Django 5.1.4 on 2025-02-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_expire_date',
            field=models.DateTimeField(),
        ),
    ]
