# Generated by Django 5.1.4 on 2025-02-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_profile_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.CharField(default='free', max_length=100),
        ),
    ]
